# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(670, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 651, 491))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setEnabled(True)
        self.tab1.setObjectName("tab1")
        self.deploy_button = QtWidgets.QPushButton(self.tab1)
        self.deploy_button.setGeometry(QtCore.QRect(260, 180, 131, 28))
        self.deploy_button.setObjectName("deploy_button")
        self.textEdit = QtWidgets.QTextEdit(self.tab1)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(12, 229, 621, 221))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 50, 611, 118))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.app_name_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.app_name_lineEdit.setObjectName("app_name_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.app_name_lineEdit)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.server_app_path_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.server_app_path_lineEdit.setObjectName("server_app_path_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.server_app_path_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.local_app_path_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.local_app_path_lineEdit.setObjectName("local_app_path_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.local_app_path_lineEdit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 10, 381, 34))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.python_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.python_radioButton.setAutoFillBackground(False)
        self.python_radioButton.setChecked(True)
        self.python_radioButton.setObjectName("python_radioButton")
        self.horizontalLayout.addWidget(self.python_radioButton)
        self.java_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.java_radioButton.setObjectName("java_radioButton")
        self.horizontalLayout.addWidget(self.java_radioButton)
        self.tabWidget.addTab(self.tab1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 621, 122))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setVerticalSpacing(12)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_13)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.source_path_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.source_path_lineEdit.setObjectName("source_path_lineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.source_path_lineEdit)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.destination_path_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.destination_path_lineEdit.setObjectName("destination_path_lineEdit")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.destination_path_lineEdit)
        self.move_directory_button = QtWidgets.QPushButton(self.tab)
        self.move_directory_button.setGeometry(QtCore.QRect(340, 190, 131, 28))
        self.move_directory_button.setObjectName("move_directory_button")
        self.switch_button = QtWidgets.QPushButton(self.tab)
        self.switch_button.setGeometry(QtCore.QRect(160, 190, 131, 28))
        self.switch_button.setObjectName("switch_button")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(200, 120, 221, 52))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.spinBox.setMaximum(65535)
        self.spinBox.setProperty("value", 300)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 631, 174))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setVerticalSpacing(12)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.server_address_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.server_address_lineEdit.setObjectName("server_address_lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.server_address_lineEdit)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.server_port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.server_port_lineEdit.setObjectName("server_port_lineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.server_port_lineEdit)
        self.username_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.username_lineEdit)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.password_lineEdit)
        self.save_setting_button = QtWidgets.QPushButton(self.tab3)
        self.save_setting_button.setGeometry(QtCore.QRect(240, 200, 131, 28))
        self.save_setting_button.setObjectName("save_setting_button")
        self.tabWidget.addTab(self.tab3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SSHTool"))
        self.deploy_button.setText(_translate("MainWindow", "Depoly App"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "app deploy log"))
        self.label_9.setText(_translate("MainWindow", "app name"))
        self.label.setText(_translate("MainWindow", "server app path"))
        self.label_2.setText(_translate("MainWindow", "local app path"))
        self.python_radioButton.setText(_translate("MainWindow", "python app"))
        self.java_radioButton.setText(_translate("MainWindow", "java war"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "app"))
        self.label_13.setText(_translate("MainWindow", "Move directory/file to another dirtory "))
        self.label_11.setText(_translate("MainWindow", "source path"))
        self.label_12.setText(_translate("MainWindow", "destination path"))
        self.move_directory_button.setText(_translate("MainWindow", "Save and Move"))
        self.switch_button.setText(_translate("MainWindow", "Switch Order"))
        self.label_3.setText(_translate("MainWindow", "M (max size)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "tool"))
        self.label_5.setText(_translate("MainWindow", "server address"))
        self.label_6.setText(_translate("MainWindow", "server port"))
        self.label_7.setText(_translate("MainWindow", "username"))
        self.label_8.setText(_translate("MainWindow", "password"))
        self.save_setting_button.setText(_translate("MainWindow", "Save setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "setting"))
